name: Twitch Auto Recorder
on:
  repository_dispatch:
    types: [twitch_online] # Сигнал от Pipedream
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Install Streamlink
        run: |
          sudo apt-get update
          sudo apt-get install -y streamlink

      - name: Record Audio 10s
        run: |
          # Замените twitch.tv/sanhez на нужный канал
          timeout 15s streamlink twitch.tv/sanhez audio_only -o stream_audio.mp4 --twitch-disable-ads || true

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: record-${{ github.run_id }}
          path: stream_audio.mp4
          retention-days: 1
